DROP TABLE ACCOUNTENTITY;

CREATE TABLE ACCOUNTENTITY (
  accountNumber BIGINT NOT NULL AUTO_INCREMENT,
  type ENUM('SAVINGS', 'CHECKING') NOT NULL,
  routingNumber INTEGER NOT NULL,
  balance FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (accountNumber)
);


DROP TABLE USERENTITY;

CREATE TABLE USERENTITY (
  userId BIGINT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR2(255) NOT NULL DEFAULT '',
  lastName VARCHAR2(255) NOT NULL DEFAULT '',
  ssn VARCHAR2(255) NOT NULL DEFAULT '',
  address VARCHAR2(255) NOT NULL DEFAULT '',
  email VARCHAR2(255) NOT NULL DEFAULT '',
  phoneNumber VARCHAR2(255) NOT NULL DEFAULT '',
  username BIGINT DEFAULT "",
  password NOT NULL DEFAULT "",
  PRIMARY KEY (userId)
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;